replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/terraform-project-382315/demo/artemis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

########################################################################################################################
###############        Enabling the app to be accessible from browser ################################################## 
########################################################################################################################

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: prod-artemis.projectxconsulting.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: prod-artemis-tls
     hosts:
       - prod-artemis.projectxconsulting.net
